### ISSUE TITLE
Add GitHub Actions to implement semantic release

### ISSUE THREAD

**Issue by masakudamatsu** [masakudamatsu/mima#2]
Once v1.0.0 is released, add the following code as `release.yml` to the `.github/workflows` folder:

```
name: 'Release with semantic versioning'
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: "Install dependencies"
        run: npm install
      - name: "Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run semantic-release
```
