### ISSUE TITLE
Custom-style the delete button for search box

### ISSUE THREAD

**Issue by masakudamatsu** [masakudamatsu/mima#203]
## Problem

Chrome and Safari show the delete button in the search box once the user enters text.

But their default style is mutually inconsistent and not in tune with the rest of design.

## Solution
```css
input[type="search"]::-webkit-search-cancel-button {
  -webkit-appearance: none;   /* Remove default */
  background-image: url("data:image/svg+xml ..."); /* cross icon (x) */
  height: 10px; /* adjust the size */
  width: 10px; /* adjust the size */
}
```
- Source: [CSS Trick](https://css-tricks.com/webkit-html5-search-inputs/#aa-styling-search-graphical-widgets)
- Use [URL-encoder for SVG](https://yoksel.github.io/url-encoder/) to convert the SVG code of a cross icon (x) into Data URI.

## Challenges

- How to change the color for dark mode?
