### ISSUE TITLE
Incorporate josh Comeau's CSS reset

### ISSUE THREAD

**Issue by masakudamatsu** [masakudamatsu/mima#474]
- [x] Disable MacOS browsers' default subpixel antialiasing

```css
body {
  -webkit-font-smoothing: antialiased;
}
```
source: https://www.joshwcomeau.com/css/custom-css-reset/#four-font-smoothing-5

- [x] Hard-wrap long words like URL (which can fix #475 )

```css
p, h1, h2, h3, h4, h5, h6 {
  overflow-wrap: break-word;
}
```
source: https://www.joshwcomeau.com/css/custom-css-reset/#seven-word-wrapping-8

- [x] Avoid the z-index mess with a popup

```css
#__next {
  isolation: isolate;
}
``` 
source: https://www.joshwcomeau.com/css/custom-css-reset/#eight-root-stacking-context-9
