### ISSUE TITLE
z-index management

### ISSUE THREAD

**Issue by masakudamatsu** [masakudamatsu/mima#476]
## Top-level
```css
div[id="__next"] {
  isolation: isolate;
}
/* Delete alert */
div[id="modal"] div[class="DivModalBackdrop"] {
  position: absolute;
  z-index: 4;
}
```

## Inside `div[id="__next"]`
```css
/* Google Map */
main div[id="map"] {
  isolation: isolate;
}
/* Buttons */
nav button[aria-label="Show menu"],
form[role="search"] button[aria-label="Search place"],
section[aria-label="controls"] button[aria-label="Track your location"] {
  position: absolute;
  z-index: 1;
}
/* Popups */
main div[class="DivPlaceInfoBackground_Wrapper"],
nav div[class="DivMenuBackground_Wrapper"],
form[role="search"] div[class="DivSearchBackground_Wrapper"] {
  position: absolute;
  z-index: 2;
}
/* Geolocation API error message */
section[aria-label="controls"] div[role="alertdialog"] div[class="DivScrim"] {
  position: absolute;
  z-index: 2;
}
section[aria-label="controls"] div[role="alertdialog"] div[class="DivPopup"] {
  position: absolute;
  z-index: 3;
}
```
